# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

def hitung_huruf_besar(teks):
  """
  Fungsi ini menghitung jumlah huruf besar dalam sebuah teks.

  Args:
    teks: String yang ingin dihitung jumlah huruf besarnya.

  Returns:
    Jumlah huruf besar dalam teks.
  """
  jumlah_huruf_besar = 0
  for huruf in teks:
    if huruf.isupper():
      jumlah_huruf_besar += 1
  return jumlah_huruf_besar

# Contoh penggunaan
teks = "Contoh Teks dengan Huruf Besar dan Kecil"
jumlah_huruf_besar = hitung_huruf_besar(teks)
print(f"Jumlah huruf besar dalam teks '{teks}': {jumlah_huruf_besar}")