# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import modul_huruf_besar

teks = "Dimulutku Ada PLANET"
jumlah_huruf_besar = modul_huruf_besar.hitung_huruf_besar(teks)
print(f"Jumlah huruf besar dalam teks '{teks}': {jumlah_huruf_besar}")